name: CI (Windows)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.11.x
              otp: 22.x
          - pair:
              elixir: 1.17.x
              otp: 27.x

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/checkout@v4

      - run: mix deps.get

      - run: mix deps.compile

      - run: mix compile

      - run: mix test --only os_windows
